// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("autoadmin.global_config_url", "file:///home/garuda/.firedragon/firedragon.overrides.cfg");
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "strict");
user_pref("browser.dom.window.dump.enabled", false);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.migration.version", 139);
user_pref("browser.newtabpage.activity-stream.impressionId", "{ee9dfef0-1d81-4678-b991-3728d03e825a}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.policies.runOncePerModification.extensionsInstall", "[\"https://addons.mozilla.org/firefox/downloads/file/3365502/sweet_dark-4.0.xpi\",\"https://addons.mozilla.org/firefox/downloads/file/4128489/darkreader-4.9.64.xpi\",\"https://addons.mozilla.org/firefox/downloads/file/4121906/ublock_origin-1.50.0.xpi\"]");
user_pref("browser.policies.runOncePerModification.extensionsUninstall", "[\"bing@search.mozilla.org\",\"amazondotcom@search.mozilla.org\",\"ebay@search.mozilla.org\",\"twitter@search.mozilla.org\"]");
user_pref("browser.policies.runOncePerModification.removeSearchEngines", "[\"Bing\",\"Amazon.com\",\"eBay\",\"Twitter\"]");
user_pref("browser.policies.runOncePerModification.setDefaultSearchEngine", "Garuda searX");
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.network.url", "");
user_pref("browser.region.update.enabled", false);
user_pref("browser.safebrowsing.downloads.remote.block_potentially_unwanted", false);
user_pref("browser.safebrowsing.downloads.remote.block_uncommon", false);
user_pref("browser.safebrowsing.downloads.remote.enabled", false);
user_pref("browser.safebrowsing.downloads.remote.url", "");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1700618563073");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1700640163073");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20231021204032");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1700618590");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.lastColdStartupCheck", 1700618590);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.toolbars.bookmarks.visibility", "always");
user_pref("browser.translation.engine", "");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[\"addon_darkreader_org-browser-action\",\"ublock0_raymondhill_net-browser-action\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"addon_darkreader_org-browser-action\",\"ublock0_raymondhill_net-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"unified-extensions-area\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":19,\"newElementCount\":2}");
user_pref("captivedetect.canonicalURL", "");
user_pref("devtools.console.stdout.chrome", false);
user_pref("distribution.garudalinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "118.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "52669f1145924058aed43535a7082cf9");
user_pref("dom.security.https_only_mode_ever_enabled", true);
user_pref("extensions.activeThemeID", "{59f619c8-220b-4a27-8918-bf1537bc060a}");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.lastAppBuildId", "20231021204032");
user_pref("extensions.lastAppVersion", "118.0.2");
user_pref("extensions.lastPlatformVersion", "118.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.addon@darkreader.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"a46f93b4-cf15-4c17-b5bf-3218550db642\",\"pictureinpicture@mozilla.org\":\"a0c0f9e1-d1e7-4bf9-a4da-45427939a0c1\",\"screenshots@mozilla.org\":\"86ee65f2-ee60-47c8-927f-60fda9e8c6b6\",\"webcompat@mozilla.org\":\"a0682293-f9bf-4e1c-9863-cdacb2736bae\",\"default-theme@mozilla.org\":\"9be5bd99-742c-4976-9ff4-5efab57a88ca\",\"addon@darkreader.org\":\"054b605e-aa36-4157-a6e5-3ca551333aa3\",\"{59f619c8-220b-4a27-8918-bf1537bc060a}\":\"1f4007f6-f7fd-481b-9bed-dd685b011ad6\",\"addons-search-detection@mozilla.com\":\"130798f3-e641-47ed-95b2-341635877d82\",\"uBlock0@raymondhill.net\":\"674813e9-0c9c-44bc-a905-eb0059453114\",\"google@search.mozilla.org\":\"86424abf-f476-4677-8b01-d919453f06bc\",\"amazondotcom@search.mozilla.org\":\"2ce2ebd2-416e-418e-8849-da471cdab85f\",\"wikipedia@search.mozilla.org\":\"c423b18c-8b31-4042-b14e-4434f0d15437\",\"bing@search.mozilla.org\":\"5dee71a7-a79b-48d6-b903-e3880746fbd7\",\"ddg@search.mozilla.org\":\"31e19787-3e3d-483c-90e9-24e5c832e262\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("intl.accept_languages", "en-US, en");
user_pref("javascript.use_us_english_locale", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.captive-portal-service.enabled", false);
user_pref("network.connectivity-service.enabled", false);
user_pref("network.http.referer.disallowCrossSiteRelaxingDefault.top_navigation", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("permissions.delegation.enabled", false);
user_pref("permissions.manager.defaultsUrl", "");
user_pref("privacy.annotate_channels.strict_list.enabled", true);
user_pref("privacy.history.custom", true);
user_pref("privacy.partition.network_state.ocsp_cache", true);
user_pref("privacy.query_stripping.enabled", true);
user_pref("privacy.query_stripping.enabled.pbmode", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.trackingprotection.emailtracking.enabled", true);
user_pref("privacy.trackingprotection.enabled", true);
user_pref("privacy.trackingprotection.socialtracking.enabled", true);
user_pref("security.sandbox.content.tempDirSuffix", "c7a090b5-93f7-4882-a9ff-7c3c4196855e");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1700618588);
user_pref("toolkit.telemetry.cachedClientID", "a97670b9-32e9-4601-ba52-eec1f5108275");
user_pref("webchannel.allowObject.urlWhitelist", "");
